
title: Kiem Duong
description: Personal web page of Kiem Duong
author: 
  twitter: DuongvanKiem
url: 'kiemduong.github.io'
twitter:
  username: Kiem Duong
social:
  name: Kiem Duong
  links:
    - twitter.com/DuongvanKiem
    - www.linkedin.com/kiemduong77
    - github.com/kiemduong
seo:
  type: Person
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

#Profile information
name: Kiem Duong
tagline: Technology Geek
pic: profile.png

#Sidebar links
website: https://kiemduong.github.io
websitealt: https://kiemduong.github.io
linkedin: kiemduong77
github: kiemduong
twitter: DuongvanKiem

style: styles
