
title: Kiem Duong
description: Personal web page of Kiem Duong
author: 
  twitter: DuongvanKiem
url: 'https://kiemduong.github.io/'
twitter:
  username: Kiem Duong
social:
  name: Kiem Duong
  links:
    - https://twitter.com/DuongvanKiem
    - https://www.linkedin.com/kiemduong77
    - https://github.com/kiemduong
seo:
  type: Person
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

#Profile information
name: Kiem Duong
tagline: Technology Generalist
pic: profile.png

#Sidebar links
website: https://kiemduong.github.io/
websitealt: https://kiemduong.github.io/
linkedin: kiemduong77
github: kiemduong
twitter: DuongvanKiem

style: styles
