
title: Kiem Duong
description: Personal web page of Kiem Duong
author: 
  twitter: ChristianElsen
url: 'https://kiemduong.github.io/'
twitter:
  username: ChristianElsen
social:
  name: Kiem Duong
  links:
    - https://www.linkedin.com/kiemduong77
    - https://github.com/kiemduong
seo:
  type: Person
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

#Profile information
name: Kiem Duong
tagline: Technology Generalist
pic: profile.png

#Sidebar links
linkedin: kiemduong77
github: kiemduong


style: styles
